### ISSUE TITLE
[Bug]: client rate limiter wait returned an error: context deadline exceeded - env launch

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#101]
![Screenshot 2024-05-13 at 5 35 12 PM](https://github.com/Facets-cloud/facets.cloud/assets/131137614/c1b767f3-bb64-476a-8d7d-462e228136e6)

**Comment by mbhandari31** [comment]
Verified by @RoguedBear (not an issue).
