### ISSUE TITLE
[Bug]: When all the resources were disabled still the launch failed. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#102]
![image](https://github.com/Facets-cloud/facets.cloud/assets/131137614/00e51109-3e06-491d-9a7c-56161f912f0a)

**Comment by mbhandari31** [comment]
Resources that are added by default should be enabled and not allowed to be disabled in the launch wizard. Else the launch/release will fail.

**Comment by mbhandari31** [comment]
Once there is a demarcation of default resources and normal resources from BE, FE team will make changes in the launch wizard and wherever needed accrodingly.
@anujhydrabadi @Swathi-P-V

**Comment by mbhandari31** [comment]
Fixed. Default resources will not be allowed to be disabled from the launch wizard now.
