### ISSUE TITLE
[Bug]: Environment Deletion requires to remove CI/CD Workflow

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#103]
Not able to delete environment because it requires deletion of CI/CD Workflow.
not able to delete the workflow because of the current design.
We need a proper user flow for deleting the entire CI/CD Workflow that has been set

**Comment by deploy-master404** [comment]
- @nachiket0310 can pick this up once the new CI/CD discussions are being developed

**Comment by mbhandari31** [comment]
Fixed.
