### ISSUE TITLE
[Bug]: Service Form, healthcheck->readiness port, liveliness port dropdown

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#104]
<img width="1079" alt="Screenshot 2024-05-14 at 12 29 34 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/2088c53c-7369-475b-a614-0ba2152e47b2">

**Comment by deploy-master404** [comment]
- @mbhandari31 and @anujhydrabadi to sync and make the api changes, post which @nachiket0310 can pick it up

**Comment by mbhandari31** [comment]
<img width="1163" alt="Screenshot 2024-05-20 at 2 20 24 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/4b49ec4f-190f-4d7d-95be-b8cdbffbf1cb">
Fixed.
