### ISSUE TITLE
[Feature/Enhancement Request]: Better naming for Settings Pages

### ISSUE THREAD

**Issue by anurag-facets** [Facets-cloud/facets.cloud#108]
**Is your feature request related to a problem? Please describe.**
It is difficult to understand which settings page is being talked about. 
1. BP > Settings
2. Env > Settings
3. Settings > General Settings

**Describe the solution you'd like**
Should be renamed to 
1. Blueprint Settings
2. Environment Settings
3. IDK 

**Describe alternatives you've considered**
NA

**Additional context**
<img width="445" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/105696056/eb399104-8e33-4fcc-8bda-4bb38e1beb34">

<img width="552" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/105696056/a7f15912-caa1-4b81-ba9d-f40b43932dcb">

<img width="552" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/105696056/5e2a9e64-9005-41ee-8ad0-e1d288acd761">

**Comment by mbhandari31** [comment]
Fixed.
