### ISSUE TITLE
[Feature/Enhancement Request]: Option to type and search in the container registry and repository while pinning an image

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#109]
<img width="1345" alt="Screenshot 2024-05-14 at 5 30 53 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/58409820-aa15-40ce-9026-9c75b315f202">

**Comment by srinikitha6** [comment]
<img width="1345" alt="Screenshot 2024-05-14 at 5 30 53 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/e3eb50d9-75e7-4fd2-92f7-1679f19cca98">

**Comment by mbhandari31** [comment]
Fixed.
