### ISSUE TITLE
[Bug]: Default values not present in service configuration page for certain fields

### ISSUE THREAD

**Issue by rr0hit** [Facets-cloud/facets.cloud#11]
The service configuration page is missing defaults (safe defaults) for a few fields:

- Restart Policy
- Service Port (If we have one for Port why not for Service Port also?)
- Memory Limit (defaults are present for other sizing fields)

<img width="1070" alt="Screenshot 2024-05-02 at 3 14 39 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/594121/025d02c6-0ea4-4001-ad10-c7391cb7d717">
<img width="1006" alt="Screenshot 2024-05-02 at 3 14 48 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/594121/494a742a-a08d-4436-bc43-6fde9c2717df">

**Comment by anujhydrabadi** [comment]
Restart Policy: added `Always` to the sample json, so fixed.

**Comment by anujhydrabadi** [comment]
Fixed (https://github.com/Facets-cloud/facets-modules/commit/50719600beb1a894649da588522404e669df64a3) (will reflect after sync)

**Comment by anurag-facets** [comment]
@rshreenivas can I close this issue?

**Comment by anurag-facets** [comment]
This issue is fixed
cc @deploy-master404 @mbhandari31 @prashantdhanke
