### ISSUE TITLE
[Bug]: postgres is disabled - but the the icon still shows coloured in the designer, the low opacity did not come

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#110]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/2c27dbb1-5cc0-4a66-886c-4aa7b76012d4">

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1549

**Comment by mbhandari31** [comment]
Fixed.
