### ISSUE TITLE
[Bug]: Environment Header shows Cloud 'Null', when not launched

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#115]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/806e9eb8-071d-442a-affc-0a3ffb236abd)

**Comment by deploy-master404** [comment]
if cloud is not there, dont show it

**Comment by mbhandari31** [comment]
<img width="704" alt="Screenshot 2024-05-21 at 2 04 28 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/2aa4efcd-af44-48b7-ba79-9c4c9b549eac">
Fixed.
