### ISSUE TITLE
[Bug]: Stack Name Length should be set to some max character

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#116]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/b58bd5a0-3839-4499-bd05-d786ea740ffd)

**Comment by deploy-master404** [comment]
- @mbhandari31 to confirm with rohit what the max stack length is and then FE can add validation + restrict accordingly
-

**Comment by mbhandari31** [comment]
Max Upper Limit 20 chars in the stack name

**Comment by mbhandari31** [comment]
environment name length should be max 25 characters - FE
Task to be created : Implement length limits in GCP base Infra

**Comment by deploy-master404** [comment]
- @mbhandari31 to confirm with BE team that it shouldn't break for any of the PAAS customers.

**Comment by mbhandari31** [comment]
Fixed. Set to 20 characters for project name and environment name
