### ISSUE TITLE
[Bug]: Modify the subtext of "Destroy" and "Delete" for better understanding

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#117]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/f9c35a47-5f25-4073-9428-ce8573095684)

Destroy will destroy the Kubernetes cluster and any dependent resources.
Delete will completely remove the environment and any associated configurations from the Control plane

**Comment by deploy-master404** [comment]
- explain what destroy and delete does

**Comment by mbhandari31** [comment]
Fixed.
