### ISSUE TITLE
[Bug]: Environment overview page should show "Launch environment" button when in stopped state

### ISSUE THREAD

**Issue by anujhydrabadi** [Facets-cloud/facets.cloud#12]
**Describe the bug**
Environment overview page should show "Launch environment" button when in stopped state.

**How to Reproduce this issue**
Create environment and go to the overview page.

**Expected behavior**
should show "Launch environment" button only, nothing else

**Screenshots**
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/129152617/c341582d-7bb8-426d-84dd-e3ccf4fc8a2e">

**Comment by mbhandari31** [comment]
@Swathi-P-V It will be fixed once environment overview page is done, right? Lets close this once we have tested both the overview pages with all the different statuses of the environment.

**Comment by deploy-master404** [comment]
<img width="1398" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/777d25a1-7e8e-42d6-b5f0-6c10fa88ddc2">


@mbhandari31 @Swathi-P-V this is how it looks like right now, do we want to add launch button in overview.

**Comment by mbhandari31** [comment]
<img width="1428" alt="Screenshot 2024-05-20 at 4 07 53 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/e550783e-e33d-4bff-9550-0f40acb39e4e">
Fixed.
