### ISSUE TITLE
[Bug]: CIDR range not populating automatically in GCP Environment

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#122]

**Comment by Swathi-P-V** [comment]
Not able to reproduce, in both create and edit flow - CIDR is being populated.
[screen-capture (13).webm](https://github.com/Facets-cloud/facets.cloud/assets/121786128/8f33cccc-30c0-4901-b14d-68b38b04205f)

Need steps to reproduce if this is happening for some other use-case.

**Comment by mbhandari31** [comment]
@Swathi-P-V confirmed with Akshay. Its working fine as expected. Hence, closing the issue.
