### ISSUE TITLE
[Bug]: Enable/Disable and Configured/Unconfigured Resources Better UX

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#125]
<img width="330" alt="Screenshot 2024-05-15 at 10 53 02 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/a6358174-97d8-46b6-87cf-4083527b5d45">

**Comment by deploy-master404** [comment]
deepak is picking this up

**Comment by mbhandari31** [comment]
Fixed.
<img width="1118" alt="Screenshot 2024-05-27 at 2 58 44 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/6ecae83a-9f61-428e-be71-0eb990056889">
