### ISSUE TITLE
[Bug]: Ref-autocomplete data API being called every time click on edit in service->env variables

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#13]
**Describe the bug**
Ref-autocomplete data API being called every time click on edit in service->env variables

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/497d89e8-e901-45c6-8314-e813b74496cc)

**More Details (please complete the following information):**

**Additional context**

**Comment by anujhydrabadi** [comment]
This has been fixed.

**Comment by mbhandari31** [comment]
@nachiket0310 fixed it and Anuj has tested it.
