### ISSUE TITLE
[Bug]: Resource Reference "KEY" UI disaligned

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#136]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/4491d606-8096-41e2-abe2-4d690d1bfc3b)

**Comment by deploy-master404** [comment]
- this will be gone with the new changes which shows this as part of the resource pop-up next to the json

**Comment by mbhandari31** [comment]
<img width="1440" alt="Screenshot 2024-05-20 at 2 11 40 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/d29ed755-9e48-4859-957d-74795081be15">
Fixed.
