### ISSUE TITLE
[Bug]: For Release Pod CPU, on using the arrow ,options turn to integers only ( including -ve)

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#140]
<img width="1263" alt="Screenshot 2024-05-15 at 11 16 04 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/021b5bbf-3d19-473d-b129-b415c19ee42c">

**Comment by deploy-master404** [comment]
- minimum value should be 0 for this component used in multiple places
- max value to be confirmed by @deploy-master404

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1548

**Comment by 4adway** [comment]
![image](https://github.com/Facets-cloud/facets.cloud/assets/108250285/be02f4c5-213f-4505-a957-d1f573dc9826)
I have added the link between the min & max values we are receiving from the backend set for these configs. @deploy-master404 please get the max values updated at the backend side as per the requirements.

**Comment by 4adway** [comment]
This is the API which I'm using: settingsService.getAllSettingsForEntityUsingGET('CLUSTER').

**Comment by deploy-master404** [comment]
Noted, will get this done 

@bhat-akshay could you help with this

**Comment by mbhandari31** [comment]
fixed.
