### ISSUE TITLE
[Bug]: Asking to type “Confirm” at some places and "Name" at some places, inconsistent with usage elsewhere in product

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#148]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/2696270f-d64c-471f-9c92-700ae3ce5cbd)

**Comment by deploy-master404** [comment]
- Type 'Confirm' in all the fields

**Comment by mbhandari31** [comment]
Fixed by @nachiket0310
