### ISSUE TITLE
[Bug]: Data shown in Release graph doesn't look correct

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#150]
all datapoints are shown at 5:30pm here. but actually the release failure was at 5:22pm, and the success ones at 5:27pm and 5:48pm
 
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/f0d34fe1-cc16-41c2-8033-3d6f72f06c17)
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/08813c84-9d07-4619-b6c7-70e007b3b768)

the graph is supposed to show data based on date and not time, need to fix it at the UI level, do not show the time, and make it cleaner in case of small amount of data
it is a daily count of releases
need a time range to be able to calculate count

**Comment by deploy-master404** [comment]
- the graph to show only dates.

**Comment by mbhandari31** [comment]
<img width="1435" alt="Screenshot 2024-05-24 at 11 25 55 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/0a6d2ca0-3eb2-4abe-b5e6-a6bad6d4603b">
Fixed.
