### ISSUE TITLE
[Bug]: Destroy started but pop-up didn't close

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#153]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/9e60ba70-2647-48c6-873d-904dacf02ae3)

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1562

**Comment by mbhandari31** [comment]
Fixed.
