### ISSUE TITLE
[Bug]: Grafana's sidebar is hiding behind our's when maximized

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#156]
<img width="1366" alt="Screenshot 2024-05-15 at 11 36 14 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/6fb44e15-fff4-4c67-9538-f5b11ceef892">

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1560

**Comment by mbhandari31** [comment]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/8956420a-c702-438f-a8e2-528dfadc474e)
Fixed.
