### ISSUE TITLE
[Bug]: Postgres is not matched by per instance modules

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#159]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/250d3660-cc21-40d4-97af-b9a312c722af)

![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/c69afb6d-b987-41bf-b820-2f3cc5da4739)

**Comment by mbhandari31** [comment]
Most likely, version passed is an integer. generate.py should handle such cases @ishaankalra

**Comment by mbhandari31** [comment]
Fixed by Aditya

**Comment by aditya-facets** [comment]
https://app.clickup.com/t/86cvdj76m 

version is set as integer, thus it did not match. Added clickup ticket
