### ISSUE TITLE
[Bug]: Newly added Projects not reflecting in the home page. These blueprint started coming up while navigating through cp, but gave the error on clicking.

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#161]
Had to refresh the entire page to access newly added blueprints. These blueprint started coming up while navigating through cp, but gave the error on clicking.
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/13bc1aff-f640-459a-9657-afcfbce53f71)

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1583

**Comment by mbhandari31** [comment]
Fixed
