### ISSUE TITLE
[Bug]: Sidepanel selection not right.

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#165]
When in user settings, it shows selected tab as something else.

<img width="1205" alt="Screenshot 2024-05-15 at 5 24 42 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/ad344990-9f2c-42f9-a388-650174b83ec3">

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1547

**Comment by mbhandari31** [comment]
<img width="1440" alt="Screenshot 2024-05-20 at 12 53 49 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/7d83b766-5f3b-40e2-bfa5-47d47abe5bfd">
Fixed. Closing the Issue.
