### ISSUE TITLE
[Feature/Enhancement Request]: Gitops at blueprint level

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#168]
1. Removes the selected account on click of create new account. 
Reproduce by - Click on create new account in choose account dropdown, it would remove the selected account. 

2. the create account popup should show some animation when the cursor is there to select. Right now it looks like an error. 

<img width="732" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/896671bf-e184-47cf-b9d0-4e211357aa6a">

**Comment by mbhandari31** [comment]
Fixed.
