### ISSUE TITLE
[Feature/Enhancement Request]: Disable 'Save' button if the account name is not added

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#170]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/42eddf3b-af44-480e-ab4c-90cfff5d7491">

**Comment by mbhandari31** [comment]
Fixed.
<img width="1437" alt="Screenshot 2024-06-06 at 10 46 37 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/7563e0ae-7e4d-49a9-b97c-1cb51a02b08f">
