### ISSUE TITLE
[Bug] : Add resources modal goes down if i scroll the page in table view

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#174]
<img width="723" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/50a525c0-7ae1-4987-9f12-9ba6799bddce">

**Comment by mbhandari31** [comment]
Fixed. Made it floating
<img width="1440" alt="Screenshot 2024-05-23 at 12 15 48 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/81bf3d37-8ba0-49d3-a087-f4b78fff5d94">
