### ISSUE TITLE
[Feature/Enhancement Request]: the subtext has fullstop (.) , some of the subtext does not have full stop

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#178]
<img width="369" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/fe5a5272-0245-43dc-816b-a05d92f2ea7c">

**Comment by krishankirtifacets** [comment]
<img width="474" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/a87b8bda-cb27-4478-9ba9-89e50d7fe388">

**Comment by mbhandari31** [comment]
Fixed
