### ISSUE TITLE
[Bug]: In schema sample volume is 8Gi but in the UI it says pattern mismatch

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#182]
Schema Sample - 
<img width="322" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/b00e608c-f5b0-495c-aeb9-4a47f74e4b40">

UI says pattern mismatch.

<img width="1124" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/7340978b-a92f-454f-8159-9ccca43a747f">

**Comment by anujhydrabadi** [comment]
This is fixed
