### ISSUE TITLE
[Bug]: EDIT & DELETE button has too much of a space

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#184]
<img width="446" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/e07bac01-2c1a-4020-9e1e-96809d863380">

**Comment by mbhandari31** [comment]
<img width="629" alt="Screenshot 2024-05-24 at 11 14 33 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/f4d26d01-e0f7-43f1-b1e2-98d91e3966d9">
Fixed.
