### ISSUE TITLE
[Bug]: wrong hyperlink redirection - postgres schema docs - k8s flavour

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#185]
**Describe the bug**
introduction hyperlink in the postgresql(k8s) documentation redirects to a github error page

**How to Reproduce this issue**
Link to CP - https://demo.control-plane-saas-cp-saas-dev.console.facets.cloud/capc/stack/pet-clinic-saas/blueprint-designer/master/resource-list/dialog/master/resource/type/postgres/name/asxvcsbv/settings

click on a postgresql resource -> go to documentation -> choose k8s flavour -> click on the hyperlink under introduction header

**Expected behavior**
accurate redirection to the right page

**Screenshots**
![Screenshot 2024-05-20 at 4 26 36 PM](https://github.com/Facets-cloud/facets.cloud/assets/158149823/41172678-4d60-4585-8e22-cee8a204c55f)
![Screenshot 2024-05-20 at 4 33 19 PM](https://github.com/Facets-cloud/facets.cloud/assets/158149823/cfdec668-4200-4087-9651-b4a9d153154f)

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Check with Infra Team.

**Comment by mbhandari31** [comment]
Fixed.
