### ISSUE TITLE
[Bug]: Not able to download or renew k8s credentials

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#186]
<img width="1440" alt="Screenshot 2024-05-21 at 3 15 35 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/1e170eb9-0254-4198-af93-e493c162cac6">

**Comment by anujhydrabadi** [comment]
The kubernetes cluster does not exist as the launch failed.

**Comment by deploy-master404** [comment]
- product team to test the working of the credentials based on cluster state. 
- make the error toasts descriptive

**Comment by mbhandari31** [comment]
Fixed
