### ISSUE TITLE
[Feature/Enhancement Request]: Unable to understand wording 

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#188]
For a release schedule, what does it mean by Available?
<img width="1387" alt="Screenshot 2024-05-21 at 5 12 30 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/bf7c5efd-c7fb-4760-a821-76e554167211">

**Comment by mbhandari31** [comment]
Same as #251
