### ISSUE TITLE
[Feature/Enhancement Request]: Instead of Kubernetes as tab name in Environment Settings, we can have as Node Management

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#191]
<img width="1336" alt="Screenshot 2024-05-21 at 5 20 39 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/9496028e-a187-45e7-9f09-ffaa391ac28f">

**Comment by mbhandari31** [comment]
Changed to Advanced Settings now.
