### ISSUE TITLE
[Bug]: On project Creation, Toast message appears related to branch 

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#194]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/6303efd0-84a0-4bc9-be68-84998eedce42)

**Comment by deploy-master404** [comment]
<img width="1374" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/17fbc93c-a9a8-4f9d-b6a4-0ed5064aba84">

this appears after enabling gitops and navigating to the designer

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1578

**Comment by mbhandari31** [comment]
Fixed
