### ISSUE TITLE
[Bug]:  enabled the resource in blueprint and proceeded to launch. But resource center was not synced with git yet and I was presented with a "Preview and Launch" dialog with the out of sync data.

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#20]
**Screenshots**
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/4ccbd27d-8886-46fd-83a5-1b544c27c4ff)
![Uploading image.png…]()

**More Details (please complete the following information):**

**Additional context**

**Comment by deploy-master404** [comment]
The solutions here would need a discussion @Swathi-P-V @deploy-master404 @mbhandari31 @krishankirtifacets @4adway 

possible scenarios to be listed down as well by @deploy-master404
