### ISSUE TITLE
[Bug]: CI/CD Workflow, environment dropdown has duplicate entries

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#200]
<img width="1122" alt="Screenshot 2024-05-21 at 11 33 17 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/31e42494-5f08-43f3-8d62-e759d9d0dbd2">
https://demo.control-plane-saas-cp-saas-dev.console.facets.cloud/capc/stack/test-project1/project-settings

**Comment by deploy-master404** [comment]
- @mbhandari31 to do a signoff and close this

**Comment by mbhandari31** [comment]
Fixed.
