### ISSUE TITLE
[Bug]: Override status filter in secrets & variables doesn't have the filter 'all', instead it is named as status.

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#208]
**Describe the bug**
The overide status filter doesn't have the filter 'all', instead it is named as status.

**How to Reproduce this issue**
Go to Projects -> secrets and variables. 

**Expected behavior**

**Screenshots**
<img width="1375" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/e2802b71-45db-4afd-8422-48a47cb983be">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
<img width="1023" alt="Screenshot 2024-05-24 at 11 15 51 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/83d08ad5-208e-4b96-a9e7-2a2f67cf64ae">
Fixed.
