### ISSUE TITLE
[Feature/Enhancement Request]: secrets & variables - change button names

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#209]
**Is your feature request related to a problem? Please describe.**
the modal already reads secrets & variables, the button doesn't need to say add secrets and variables again. 
- we already 

**Describe the solution you'd like**
Change the button names to 'Add' and the 'edit overrides' button to 'Overrides'. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed
