### ISSUE TITLE
[Bug]: I destroyed my dev environmnet. The immediate next screen shown is "Environment Launch Wizard"/

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#21]
**Describe the bug**

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**More Details (please complete the following information):**

**Additional context**

**Comment by deploy-master404** [comment]
- should be fixed once @Swathi-P-V  merges the header changes

**Comment by Swathi-P-V** [comment]
@deploy-master404 @mbhandari31 What is the expected behaviour?
After my header changes, Destroy is available only in settings and on destroy it is navigating to releases page - is it expected behaviour?

**Comment by mbhandari31** [comment]
@Swathi-P-V This is the expected behavior. As mentioned in the comment by @deploy-master404, this issue will be fixed with your new header changes. Once they are merged, we can close this issue next week.

**Comment by mbhandari31** [comment]
Closing the issue as it is fixed
