### ISSUE TITLE
[Bug]: Secrets & Variables Redirection from env overview page

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#210]
**Describe the bug**
when environment overview is opened, and secrets & variables is clicked on from one of the cards there, the side panel opens, but on exiting, it takes you outside environments and leaves you in the projects page. 

**How to Reproduce this issue**
refer above.

**Expected behavior**
it should come back to environment overview page as you were redirected from there. 

**Screenshots**
<img width="1369" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/f94f5c7d-6aa0-4fc5-a609-216ce77f2f96">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed.
