### ISSUE TITLE
[Bug]: Branch Selector Issue while creating a project

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#211]
**Describe the bug**
when i created a project, it redirected me to the blueprint page inside the project for a split second. And then it redirected me to the homepage with this error.

**How to Reproduce this issue**
Create a project

**Expected behavior**
it should navigate inside the project and open the blueprint tab.

**Screenshots**
<img width="1369" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/7c12a207-1704-485c-a0a4-2934f82604ef">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed.
