### ISSUE TITLE
[Bug]: Error toast saying branch main not found when master is selected

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#213]
**Describe the bug**
Gitops is enabled, user has added master as the branch and when the user redirects to the blueprint, it shows an error toast saying, branch main not found.

**How to Reproduce this issue**
enable gitops, choose master branch and navigate to the blueprint page.

**Expected behavior**
the resources should show clearly and the master branch should be selected. 

**Screenshots**
<img width="981" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/5482c538-c4bd-476f-a6a0-c122f5153367">

<img width="981" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/1e52123f-3a85-4add-82fb-556e5f4b9adf">

**More Details (please complete the following information):**

**Additional context**

**Comment by deploy-master404** [comment]
@anujhydrabadi  -- 
 this happens when while enabling gitops, someone enters a branch different from the existing one
in our repos, branch is main
If someone enters master, .git folder must have main ka kistory, so it fails, not sure

**Comment by mbhandari31** [comment]
Fixed.
