### ISSUE TITLE
[Feature/Enhancement Request]: Modal UX copy inconsistency

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#214]
**Is your feature request related to a problem? Please describe.**
The modal doesn't have uniform wording.

**Describe the solution you'd like**
Make the text as 'Confirm' everywhere. 

**Describe alternatives you've considered**

**Additional context**
<img width="1379" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/b119c6f6-4e14-4e75-8b4c-f5450b45419e">

**Comment by mbhandari31** [comment]
Fixed.
