### ISSUE TITLE
[Feature/Enhancement Request]: make flavour a dropdown in resource settings

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#215]
**Is your feature request related to a problem? Please describe.**
- currently if i have to view available flavours of the resource, i have to change it from the project settings, change primary cloud and then add resource again.

-i can currently edit it but only the name, it would be better if i knew the available flavours while editing the resource

**Describe the solution you'd like**
a dropdown in the flavour section of the resource that shows me the available resources. 

**Describe alternatives you've considered**

**Additional context**
<img width="1379" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/09ead804-7f3b-41d2-996c-d064748917bc">

**Comment by mbhandari31** [comment]
Fixed.
