### ISSUE TITLE
[Feature/Enhancement Request]: dropdown texts on the other end

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#216]
**Is your feature request related to a problem? Please describe.**
dropdown texts on the other end

**Describe the solution you'd like**
the dropdown texts should be next to the tickboxes

**Describe alternatives you've considered**

**Additional context**
<img width="1379" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/2961c4ea-6d8f-48a4-8988-2e21abb6343c">

**Comment by mbhandari31** [comment]
Fixed.
