### ISSUE TITLE
[Feature/Enhancement Request]: disabled field toggle in resources page

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#217]
**Is your feature request related to a problem? Please describe.**
In the resource settings, disabled is the field name, but the toggle is switched on, this is confusing as they're opposing behaviours. 

**Describe the solution you'd like**
the field name should be enabled.

**Describe alternatives you've considered**

**Additional context**
<img width="1379" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/eb274eae-4d82-401f-88be-d112579bbf0f">

**Comment by mbhandari31** [comment]
Fixed.
<img width="1336" alt="Screenshot 2024-05-27 at 2 57 53 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/b6212f8a-3def-4851-afab-194865ef1012">
