### ISSUE TITLE
[Bug]: Environment type inconsistency even after changing type

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#219]
**Describe the bug**
#1 I created a schedule and confirmed my changes. I switched back to regular and I confirmed my changes again. When I switched back to time sensitive again, my previously added values were still stored. I’m not sure whether this was intended behaviour or not.
#2 The bot performed a scale down release when time sensitive was switched on. When I changed the setup back to Regular, the release page was still showing “Next Scale up will start  in X days X hours X mins….

**How to Reproduce this issue**
Refer above

**Expected behavior**
if the environment is set as regular, then no schedule should be active

**Screenshots**
<img width="981" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/e0125cd9-f409-4879-8cfd-f07a8367bda0">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed.
