### ISSUE TITLE
[Feature/Enhancement Request]: env settings -> releases field name and subtext unclear

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#220]
**Is your feature request related to a problem? Please describe.**
this part is a bit unclear. Available text seems weird. subtext for the other two is missing.

**Describe the solution you'd like**
change name from available to

**Describe alternatives you've considered**

**Additional context**
<img width="830" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/a86a5e40-e05c-4f8b-92bf-e557627b4c5b">

**Comment by mbhandari31** [comment]
Fixed.
