### ISSUE TITLE
[Bug]: release pod mem and cpu fields is empty when switching tabs

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#223]
**Describe the bug**
In releases tab, release pod memory and cpu show as blank when tabs are switched. they also appear to be slow and loading slowly. 

**How to Reproduce this issue**
open the env settings page, navigate to releases tab, exit the settings and open it again. 

**Expected behavior**
the release pod memory and cpu fields should be prefilled with the values and should not take much time while loading

**Screenshots**
<img width="1379" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/ac1c0dd5-e712-4b6d-acbe-36bd53d41f53">

**More Details (please complete the following information):**

**Additional context**

**Comment by deploy-master404** [comment]
- this might be an api timing issue, once akshay makes the yaml for the settings, this would be faster

**Comment by mbhandari31** [comment]
fixed.
