### ISSUE TITLE
[Bug]: MySQL RDS 0.1: does not work without spec.size.writer.replica_count

### ISSUE THREAD

**Issue by anujhydrabadi** [Facets-cloud/facets.cloud#226]
**Describe the bug**
This should not be the case as replica count is a deprecated field.

**Stack trace**
│ error: unsupported attribute
│
│ on ../modules/1_input_instance/aws_rds_mysql/outputs.tf line 5, in locals:
│ 5: for index in range(var.instance.spec.size.writer.replica_count) :
│ ├────────────────
│ │ var.instance.spec.size.writer is object with 1 attribute "instance"
│
│ this object does not have an attribute named "replica_count".
╵
********** starting legacy_post since error was encountered ********

**Comment by mbhandari31** [comment]
Fixed.
