### ISSUE TITLE
Resource node popover UI Issue

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#228]
On hove the popover comes which is working fine, but if a text is too long then it overflows and a scroll bar appears. When I move over the popover to scroll it, it disappears.

Solution could be to have the popover length based on the content inside.

<img width="1309" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/2a3176b4-2ab6-433f-a8d4-d77f36688a55">

**Comment by mbhandari31** [comment]
Pop-up removed. Fixed.
