### ISSUE TITLE
"Flavour k8s and version 0.1 not supported. Enter valid flavour and version to get the form." Error 

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#229]
Is this supposed to happen or is this a bug? @mbhandari31 @deploy-master404 

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/069889ea-878c-4035-bec6-0188ad5694ca">

**Comment by dsaini63** [comment]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/65fe0d73-347c-4d1e-9d70-170ea2fe7f53">

this is definitely a bug

**Comment by dsaini63** [comment]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/4acfc98f-6e25-48e6-b26e-7369a0f8c4c5">

**Comment by mbhandari31** [comment]
Fixed.
