### ISSUE TITLE
[Bug]: Need to fix the stop time which should be less than start time for same day

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#235]
<img width="1436" alt="Screenshot 2024-05-27 at 4 26 26 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/834486fc-af1d-4916-b3d6-80c7f3e9a4f8">

**Comment by deploy-master404** [comment]
- availability rules api being called even when regular environment is selected
- save changes button is still visible when i'm not making any changes in the vpn, releases and time sensitive tabs.
- set to time sensitive to revert to regular then don't call update api - @SushmithaFacets 
- discard changes removes selected options.
