### ISSUE TITLE
Redirection not happening properly.

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#237]
<img width="863" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/05602b66-3c14-4ca0-9bc7-d8e7ae49c65c">

on clicking on the environment level resource name above, another tab opens up and the loader keeps on spinning but the blueprint level resource doesn't open.

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/09fa02fe-91dd-48e2-922a-51c758c285a2">

**Comment by deploy-master404** [comment]
- this page won't be there with the new UI, so this bug is invalid
