### ISSUE TITLE
Clicking on Back closes the modal

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#238]
<img width="606" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/ae227e97-3493-49e9-94d4-feb78efa4919">

Either we can reopen the add resources panel if we decide to keep it "back".

OR

we can change the text to Cancel and keep the same behaviour (modal closes on clicking of back)

**Comment by mbhandari31** [comment]
Fixed. Back button renamed to Cancel
