### ISSUE TITLE
[Bug]: Unable to choose service type even though the tooltip suggests I can choose from 4 types

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#240]
**Describe the bug**
Unable to choose service type even though the tooltip suggests I can choose from 4 types

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**
Either the tooltip should be written better or the dropdown should have more options

**Screenshots**

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Updated the tooltip as per the plan. Other types coming soon.
