### ISSUE TITLE
[Bug]: Service form -> Autoscaling block has incorrect fields. 

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#241]
**Describe the bug**
fields like RPS and PPS shouldn't be present as they aren't in BE

**How to Reproduce this issue**
https://demo.control-plane-saas-cp-saas-dev.console.facets.cloud/capc/stack/pet-clinic-saas/blueprint-designer/master/resource-list/dialog/master/resource/type/service/name/service-1/settings

**Expected behavior**

**Screenshots**
<img width="1315" alt="Screenshot 2024-05-29 at 12 16 46 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/5ec8aa69-70a5-4c69-8f36-0a8450eb5026">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed. Removed RPS and PPS blocks.
