### ISSUE TITLE
[Bug]: SidePanel Selection not coming correctly for the selected page

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#244]
If I click on browser back from any page, the selection of the icon in the side panel is not correct.
https://github.com/Facets-cloud/facets.cloud/assets/162995672/6becbe53-cbd5-473a-b840-71553e86eb28

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1607
