### ISSUE TITLE
[Bug]: On Resource Hover -> tooltip is always left aligned, it hides behind the left nav.

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#245]
**Describe the bug**
On Resource Hover -> tooltip is always left aligned, it hides behind the left nav.

**How to Reproduce this issue**

**Expected behavior**

**Screenshots**
<img width="1138" alt="Screenshot 2024-05-30 at 10 13 24 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/564e8d30-5ed9-4aa2-9395-d5e384eb5559">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Not applicable anymore
