### ISSUE TITLE
[Bug]: service form

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#246]
**Describe the bug**
make subtext of enable/disable host affinity better

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
<img width="665" alt="Screenshot 2024-05-30 at 10 15 45 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/cb5065d6-1181-405a-a073-2b7734a04031">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed.
