### ISSUE TITLE
[Bug]: Add Service Modal inconsistencies

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#247]
**Describe the bug**
Lot of empty space - doesn't look good
Non-aligned text input boxes
Add More button can be below the line to ensure one service is divided by another service with that line.

**Screenshots**
<img width="1381" alt="Screenshot 2024-05-30 at 10 17 47 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/8f0ca828-b122-4b28-b839-25d4da43659b">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed.
