### ISSUE TITLE
[Bug]: inconsistent naming ephemeral environments

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#249]
**Describe the bug**
ephemeral and time sensitive user interchangeably, needs to be consistent 

**Screenshots**
<img width="1372" alt="Screenshot 2024-05-30 at 10 26 22 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/3016e89a-4332-4a7e-a6aa-dd5d160ecc24">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed
