### ISSUE TITLE
[Bug]: User is unclear if they need to add multiple ingress'

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#250]
**Describe the bug**
The add more ingress button was unclear to the user, it needs to be clear and the subtext needs to be descriptive. 

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
<img width="1376" alt="Screenshot 2024-05-30 at 12 00 55 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/28280757-b87e-4875-a68e-74962966102d">

**More Details (please complete the following information):**

**Additional context**

**Comment by deploy-master404** [comment]
- This needs to be fixed for all add resource modals from which multiple versions can be added.

**Comment by mbhandari31** [comment]
Fixing it with #247
