### ISSUE TITLE
[Bug]: Environment Settings UX Content

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#251]
**Describe the bug**
Incorrect and content that is not precise needs to be changed

**Screenshots**
1. <img width="1375" alt="Screenshot 2024-05-30 at 12 12 54 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/74ce4167-835c-41ed-9f3f-f8905da3aa82">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed
