### ISSUE TITLE
[Bug]: Add resource UX content

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#252]
**Describe the bug**
1. The subtext is both in camel case and normal -- Unique Name for your service -> Unique name for service.
Unique name for service should be -> Give a unique name for service
2. Choose a resource version or leave it empty to use the default version.
3. Content to be given. 
4. Content to be given. 
5. Enable host anti-affinity to avoid resources placing on the same physical host.(check with infra)
6. I will use CI/CD set in project settings.
7. Environment Artifacts ->
Directly deploy the image in respective environment.

**Screenshots**
1. <img width="981" alt="Screenshot 2024-05-30 at 12 19 04 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/3ca3441d-8932-4d70-a290-a5f305e40347">
2. 
<img width="789" alt="Screenshot 2024-05-30 at 12 22 07 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/b345f876-5dac-4249-86ce-6025757ff21b">

3. 
<img width="984" alt="Screenshot 2024-05-30 at 12 22 22 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/ac7ccf88-371e-4ebc-bae0-777f1902ab91">

4. 
<img width="828" alt="Screenshot 2024-05-30 at 12 30 22 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/54e90403-e0c7-4016-9ecd-56e3ceff356f">

5. 
<img width="665" alt="Screenshot 2024-05-30 at 10 15 45 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/0c3f1ad9-4b91-4ab3-ba43-9dda92ac37bf">

6. 
<img width="821" alt="Screenshot 2024-05-30 at 12 34 21 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/e580a8cb-32ed-4374-bb1e-db984fe8a289">

7. 
<img width="878" alt="Screenshot 2024-05-30 at 12 36 30 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/ada01b88-4f75-439e-9ae2-cd9f5d28aad1">

**More Details (please complete the following information):**

**Additional context**
<img width="984" alt="Screenshot 2024-05-30 at 12 22 22 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/8a71019b-83f7-4ba7-8f22-d8b5b0b66eaa">

**Comment by mbhandari31** [comment]
Fixed.
