### ISSUE TITLE
[Bug]: Save Changes button status doesn't change

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#253]
**Describe the bug**
1. Save Changes button status doesn't change
2. remove the tooltip for save changes

**How to Reproduce this issue**
Make changes in the general tab of the service configuration and then revert back to the old changes

**Expected behavior**
the save changes button should also revert to normal once the changes have been reverted

**Screenshots**
<img width="1272" alt="Screenshot 2024-05-30 at 12 48 00 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/bd875c5e-0d0e-4f66-8929-23f1cf69d28a">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed.
