### ISSUE TITLE
[Bug]: mandatory field in serivce was set empty yet the resource was saved

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#27]
**Describe the bug**

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**More Details (please complete the following information):**

**Additional context**

**Comment by anujhydrabadi** [comment]
This is fixed: https://github.com/Facets-cloud/facets-modules/commit/d2365857b05368b023978e58e6f8e11407f6bcda

**Comment by anujhydrabadi** [comment]
Just needed a fix in the sample json, can be closed
