### ISSUE TITLE
[Bug]: Availability zones going wrong at the time of relaunch 

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#270]
this is the second time it is happening not sure how to reproduce but somehow after a failed launch when launching again, the launch wizard comes up with data from previous steps auto populated directly at the last page the availability zone is changed from ap-southeast to ap-south causing the entire VPC to recreate and the cluster to be eventually deleted
the screenshot shows this discrepancy

![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/fecffe92-f315-42cc-91b2-18deb2ca7a2a)

https://demo.control-plane-saas-cp-saas-dev.console.facets.cloud/capc/petclinic-kirti-demo/cluster/6641f48f82bc080007d47ad4/release-details/6666f8a07aae0b0007abd7bc
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/d634bcb4-910d-4067-92cd-77550d523a8e)

![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/d0cb627a-8a6f-4e2c-ba3f-82258c08b35d)

no way to deselect (unless you change the main region itself to reset this field)
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/ad72582f-8f25-46f5-8174-6a59169e5eab)

**Comment by 4adway** [comment]
Working on this.
