### ISSUE TITLE
[Bug]: Title text of the modal needs to be better. It looks unprofessional not actionable. - As in What Let's Start

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#273]
<img width="459" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/e1c81ab1-4a4c-4726-bac4-cdbad033ca85">

**Comment by Swathi-P-V** [comment]
What text it should be changed to?

**Comment by mbhandari31** [comment]
Fixed. pop-up changed.
