### ISSUE TITLE
[Bug]: Link your github account Issues 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#274]
1. I should know clearly what my github account will be used for here
2. The subtext talking about unique identifier is hard to infer, make it very simple and also explain what it will be used for?
3. The same will be used while launching environments. -> This does not make sense here. 
4. Enter github account name -> User would go and search for the account name. Just put it -  enter name for the account or enter name. 

<img width="218" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/6fa33085-0b5d-4d31-acb3-2a20e34732e5">

<img width="748" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/f71e9851-432e-4fcd-a73f-b5ed86d0e759">
<img width="709" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/5f2d09e7-1aae-4a82-8176-5aad0d979c69">

**Comment by mbhandari31** [comment]
Fixed.
