### ISSUE TITLE
[Bug]: Dangling links to Resource Center page

### ISSUE THREAD

**Issue by SushmithaFacets** [Facets-cloud/facets.cloud#277]
**Describe the bug**
If we are planning to remove Resource Center then we need to update the url of this button as it is currently navigating user to resource level pages. 
<img width="705" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/96563449/d4ce9d44-bf75-4ee4-b4fa-3f40ac997fbf">

<img width="670" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/96563449/1dfe982d-5859-4d92-a660-ad39c208eb9c">

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed.
