### ISSUE TITLE
[Bug]: We need to review all statuses shown in kubernetes view. It says unknown, but pod is running

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#28]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/dad189e4-129d-4991-a6cb-72ee1010d7f9)

**Comment by deploy-master404** [comment]
- this is only coming for a fraction of a second, we wont be able to do a fix as of now

@mbhandari31 to confirm this with @bhat-akshay

**Comment by anujhydrabadi** [comment]
Also, it is showing `ContainerCreating` for `InvalidImageName`
This needs to be fixed @mbhandari31

**Comment by deploy-master404** [comment]
this has been fixed by @bhat-akshay , confirmed by @anujhydrabadi
