### ISSUE TITLE
[Bug]: env settings not reading saas defaults

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#280]
**Describe the bug**
env settings not reading the saas defaults, instead it's reading the default values set for paas.

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
<img width="1393" alt="Screenshot 2024-06-19 at 6 23 58 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/6a152514-edc2-497c-abd4-45ba1592f30a">

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
Fixed. Confirmed with Akshay. Closing it.
