### ISSUE TITLE
[Bug]: post clicing on the launch button got a blank screen

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#286]
https://4711678094.control-plane-saas-cp-production.console.facets.cloud/capc/test-kirti-4711678094/cluster/6638abd8da6cb700074c31cd/releases

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/cb4f35f7-2ffd-4949-8ef9-8e84ade41550">

**Comment by mbhandari31** [comment]
Fixed.
