### ISSUE TITLE
[Bug]: Launch Failed for Azure env. Resources only having azure flavor or k8s flavor were enabled in this env. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#287]
│ error: reference to undeclared local value
│
│ on level2/main.tf line 329, in module "service_monitoring_service-k8s-monitoring-monitoring":
│ 329: service_attributes = local.module__
│
│ a local value with the name "module__" has not been declared.
╵
╷
show less
____________________________________________________________________
│ error: reference to undeclared local value
│
│ on level2/main.tf line 351, in module "service_monitoring_azurestoragecontainer-default-monitoring":
│ 351: service_attributes = local.module__
│
│ a local value with the name "module__" has not been declared.
╵

traceback (most recent call last):
file "/sources/primary/capillary-cloud-tf/tfmain/scripts/iac_migration.py", line 196, in
run_migrations(args.release.lower(), os.environ["cloud"].lower(), state)
show less

**Comment by mbhandari31** [comment]
Fixed.
