### ISSUE TITLE
[Bug]: Azure env failed due to no artifact. It should not fail the release. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#288]
│ error: unsupported attribute
│
│ on level2/input_service_servicek8s.tf.json line 22, in locals.input_service_servicek8s.spec.release:
│ 22: "image": "${local.module_blueprint_self.artifacts.test-kirti-4711678094-servicek8s}"
│ ├────────────────
│ │ local.module_blueprint_self.artifacts is object with no attributes
│
│ this object does not have an attribute named
│ "test-kirti-4711678094-servicek8s".
╵
********** starting legacy_post since error was encountered ********

**Comment by mbhandari31** [comment]
Fixed
