### ISSUE TITLE
[Bug]: Node type has a default value, it didn;t show up in the launch wizard. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#292]
https://4711678094.control-plane-saas-cp-production.console.facets.cloud/capc/test-kirti-4711678094/cluster/6638abd8da6cb700074c31cf/releases/dialog/launch

<img width="1366" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/5437d1aa-568d-464d-a7c1-0dbee2030903">

**Comment by mbhandari31** [comment]
Fixed
