### ISSUE TITLE
[Bug]: after enabling gitops, designer did not load

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#293]
<img width="1440" alt="Screenshot 2024-06-20 at 3 23 43 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/0a7a62f4-f21f-4bf6-9024-6a9085f140a5">

**Comment by mbhandari31** [comment]
Confirm with @SushmithaFacets

**Comment by mbhandari31** [comment]
Fixed.
