### ISSUE TITLE
[Bug]:Name Hardcoded in Service Monitoring 

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#296]
**Describe the bug**
Name Hardcoded in Service Monitoring and hence it is not working

**How to Reproduce this issue**
Add the detailed steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**More Details (please complete the following information):**

**Additional context**

**Comment by mbhandari31** [comment]
confirm with @4adway

**Comment by mbhandari31** [comment]
Fixed by Anshul.
