### ISSUE TITLE
[Bug]: Launch Configuration is not persistent after launch fails. 

### ISSUE THREAD

**Issue by deploy-master404** [Facets-cloud/facets.cloud#3]
**Describe the bug**
when launch fails, it asks me to enter vpc id, time zone etc details again
it should be saved for next time I trigger launch

**How to Reproduce this issue**
fill all the details in the launch wizard for env launch and trigger the launch, once it fails

**Expected behavior**
the saved changes must be persistent even if the launch fails and while the user tries to trigger it, they must have changes saved.

**Screenshots**
<img width="1300" alt="Screenshot 2024-04-30 at 2 14 46 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/8381142a-7d2a-46af-a4f5-0f2b16990f72">

**More Details (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave

**Additional context**

**Comment by mbhandari31** [comment]
@Swathi-P-V:  Aadway can pick it up on Monday and close it.
