### ISSUE TITLE
[Bug]: After enabling/disabling a resource, it's not getting refreshed

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#31]
In the gcp-infra-dev, I have enabled a service but I could see the page is not refreshed. And, the tabs like monitor are not accessible. They were accessible after refreshing. After disabling, I could access the m

It's on googlechrome.
<img width="1378" alt="Screenshot 2024-05-06 at 12 03 58 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/51a4b86d-0cde-467a-b8c8-cf13367593ee">

**Comment by mbhandari31** [comment]
Fixed. Tested in multiple CPs for multiple users.
