### ISSUE TITLE
[Bug]: Ingress Overview is not loading

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#32]
Ingress Overview is not loading. It's giving white-label error.

<img width="1381" alt="Screenshot 2024-05-06 at 4 59 22 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/9d0a5a1d-c3d9-44ee-9d96-4652dc32b760">

**Comment by deploy-master404** [comment]
- happens when iframe url or value is not present/valid. 
- this is an infra related issue @mbhandari31 please get the clarity for this

**Comment by bhat-akshay** [comment]
@mbhandari31 Ingress overview grafana dashboard is not present in the blueprint. Users have add the dashboard to get this page. Please confirm if this dashboard has to added to saas template.

**Comment by mbhandari31** [comment]
Fixed.
