### ISSUE TITLE
[Bug]: Grafana dashboard is not visible

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#33]
In the service, Grafana dashboard is not loading.
<img width="1380" alt="Screenshot 2024-05-06 at 5 01 57 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/8f193d4c-80f2-47b3-bae1-f0644a6b5123">

**Comment by deploy-master404** [comment]
- would need to add a cue to add 'add-on' resources from this page

**Comment by mbhandari31** [comment]
Fixed.
