### ISSUE TITLE
[Bug]: Ingress overview displays 500 error

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#35]
https://4711678094.control-plane-saas-cp-production.console.facets.cloud/capc/kirti-prashant-4711678094/cluster/663381f1cf4e14000781afec/resources/type/ingress/resource/pc-ingress/ingress-overview-dashboard

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/8fae8140-1aa5-4546-9c93-d495d0b527aa">

**Comment by deploy-master404** [comment]
this is similar to #32

**Comment by deploy-master404** [comment]
- someone from infra would be adding the default resources to the base blueprint

**Comment by mbhandari31** [comment]
Duplicate of #32 
Closing it.
