### ISSUE TITLE
[Bug]: Create user form has prefilled user details

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#37]
Whenever clicking on the "Create user", it's prefilled with my details.
 

https://github.com/Facets-cloud/facets.cloud/assets/106736846/b67b39cd-70de-4b3b-8424-7ca157f7babe

**Comment by mbhandari31** [comment]
@SushmithaFacets Please resolve this bug

**Comment by mbhandari31** [comment]
Fixed by Sushmitha.
