### ISSUE TITLE
[Bug]: Queued release details blueprint spec redirection not working

### ISSUE THREAD

**Issue by anujhydrabadi** [Facets-cloud/facets.cloud#38]
**Describe the bug**
Queued release details blueprint spec redirection not working

**How to Reproduce this issue**
Make a queued selective release, go to 'i' button, and go to blueprint spec of any resource.

**Expected behavior**
Expect redirection to happen.

**Screenshots**
![image](https://github.com/Facets-cloud/facets.cloud/assets/129152617/6dee030c-5a98-4659-87ba-ad9380b46a06)

**Comment by Swathi-P-V** [comment]
This has been fixed.
