### ISSUE TITLE
[Feature/Enhancement Request]: UX Issues in the overrides view table page 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#39]
1. There's no where we write that its environment level overrides, either we should write a subtitle or the change name of the page. 
2. Button says 'Edit overrides', but one can add overrides as well. Should it be Add/Edit overrides or Just Add overrides and some icon against every overrides in the table. 
2.1. Since 'Edit overrides' is the primary action on this page, the button should be a primary button, right now it is a secondary button. 
3. Calling ' keys '  as 'path' is a bit confusing. I got confused that are we doing something with references here. 
4. Back button closes the modal. I expect back button to take me back to the previous screen. Ideally If I have to close the modal, I would click outside in the designer or click on 'X' button. Right now there's no 'x' button to close. 
4.1. Happened 2-3 times while testing, sub consciously I clicked on back to go back to table view instead of 'view table button'. 

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/9f4475e1-6bfe-4abb-b17b-a2af6d1a38bc">

**Comment by mbhandari31** [comment]
Fixed.
