### ISSUE TITLE
[Bug]: in brackets there are blueprint default values for keys but for the environment name form field it shows release stream (DEV) in the bracket. This would confuse the users, what exactly is in the bracket. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#45]
<img width="525" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/e18f34b5-7b76-4821-8dce-a93a6dfbd015">

**Comment by deploy-master404** [comment]
- This has been fixed, env name is now not shown in the top of the form in resource overrides
@mbhandari31 please confirm this once 

![Screenshot 2024-05-17 at 8 55 30 AM](https://github.com/Facets-cloud/facets.cloud/assets/158149823/5a195f9c-7ba9-4004-8393-076f5b480dd0)

**Comment by mbhandari31** [comment]
Resolved.
