### ISSUE TITLE
[Bug]: Three secondary buttons here, the UI should help me with different buttons to take a decision. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#47]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/2d2f4755-31ab-450e-94f6-c1119e936241">

**Comment by deploy-master404** [comment]
![Screenshot 2024-05-17 at 8 57 17 AM](https://github.com/Facets-cloud/facets.cloud/assets/158149823/564e13f5-e197-46c8-882a-504c96efaeaf)

- sync with git has moved to the header on top
- we should make 'Add New' as the primary button and 'Edit Overrides' as the second button. 
- @deploy-master404 to validate if overrides is an accurate description of the button/feature.
- @deepak to verify if this is a feasible solution.

**Comment by deploy-master404** [comment]
<img width="1369" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/35638f2e-4e4b-42ca-8a72-cfa6680c0f8d">

same issue raised by @srinikitha6 as well

**Comment by mbhandari31** [comment]
<img width="1437" alt="Screenshot 2024-05-23 at 12 23 29 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/726bc11f-c8b9-4427-b768-6a3b802e5eb2">
Fixed
