### ISSUE TITLE
[Feature/Enhancement Request]: Can this be a clear list of environments and I can just select

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#49]
right now, I need to click on dropdown to see the environment. Not a major one - but if we show the list directly and ability to select, so user won't have to think a lot to get the context. 

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/90465a6d-eb8b-4741-8fa9-9a8d2244a92d">

**Comment by deploy-master404** [comment]
- this modal will be going away with the new enhancement and the user will land on the page with a default environment selected.

**Comment by mbhandari31** [comment]
Fixed.
