### ISSUE TITLE
[Bug]: secrets and variables : overrides -> no action button to override the values

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#50]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/5c815904-ecd5-4762-837c-ecc18c7e292d">

**Comment by mbhandari31** [comment]
<img width="1297" alt="Screenshot 2024-05-24 at 11 15 11 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/ad3ca943-5f43-4bd2-8ca8-a2f545b61055">
Fixed
