### ISSUE TITLE
[Bug]: action icon not aligned to the header

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#51]
got the actions button on refersh of the page. But the actions button are not aligned to the header. 
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/baffae9c-21eb-4db5-a098-2e2eeb1ee26c">

**Comment by deploy-master404** [comment]
- Action buttons are not displayed when i land for the first time but is shown on refresh. 
- alignment needs to be fixed as well

**Comment by mbhandari31** [comment]
<img width="1354" alt="Screenshot 2024-05-24 at 11 16 48 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/8d3b8c54-841b-4f2c-981f-79d97d6d9703">

Fixed.
