### ISSUE TITLE
[Feature/Enhancement Request]: modal should have a title telling me what page I am in and what I should be doing here to keep the context. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#52]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/06fba10a-7bb2-420d-bf49-09efd7823e6e">

**Comment by deploy-master404** [comment]
We would need to introduce a clear header in the side panel, that indicates the user what this side panel is and what they can do from here

Header: "Override Secrets & Variables"
Subtext: "Adjust environment-specific values here. Changes made will not affect the default settings but will override them in selected environments.

**Comment by mbhandari31** [comment]
Fixed
<img width="1405" alt="Screenshot 2024-06-26 at 6 20 30 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/c2f933db-504d-4771-8308-8e13b992d66b">
