### ISSUE TITLE
[Bug]: editing secrets value does not retain the 'asterik' symbol for the value, rather it shows the direct text in display view of the table. 

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#54]
![image](https://github.com/Facets-cloud/facets.cloud/assets/131137614/52006107-ba83-4dae-ae21-2dfbc4ef4988)

**Comment by mbhandari31** [comment]
@krishankirtifacets  One needs to click on "Save Changes" to not see the updated value. We are showing this value only to the user who has edited it and it is shown only till the time he/she clicks on "Save Changes"
