### ISSUE TITLE
[Bug]: We should explicitly ask for selecting environment in the dropdown

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#55]
<img width="698" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/131137614/9e84d2f7-16c6-49c5-bb14-87fa19164517">

**Comment by mbhandari31** [comment]
<img width="1023" alt="Screenshot 2024-06-27 at 11 45 43 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/40eea758-60d2-49fa-8e3b-d376526d1500">
Fixed.
