### ISSUE TITLE
[Feature/Enhancement Request]: Auto-inject tooltip is needed

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#60]
What do we mean by Auto-inject? What happens if they turn it on and if they don't turn it off? These questions should be answered in the tooltip.

**Comment by deploy-master404** [comment]
The tooltip is visible in facets demo, need to make it visible in saas also @Swathi-P-V

**Comment by mbhandari31** [comment]
Fixed
