### ISSUE TITLE
[Feature/Enhancement Request]: Add variable button is confusing/misleading

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#61]
Button has Add Variable but they can also add Secret which is confusing and misleading to the new users.
<img width="1118" alt="Screenshot 2024-05-08 at 6 07 22 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/0e5ea5b5-2441-4839-a387-7357a5f32718">

**Comment by mbhandari31** [comment]
Fixed.
