### ISSUE TITLE
[Bug]: Secrets/Variables Overridden column filter options are wrong

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#62]
Overriden is the column with Status and Overridden options in the filter which is wrong. Overriden status should be either yes or no.
<img width="1331" alt="Screenshot 2024-05-09 at 12 02 25 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/16c6b1d8-0ccd-4d96-b173-95932457f1d3">

**Comment by srinikitha6** [comment]
Also, there is no way to view all the secrets and variables after selecting an option in the filter.

**Comment by nachiket0310** [comment]
<img width="1421" alt="Screenshot 2024-05-16 at 12 36 34 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/107979705/1d1d5638-5765-43ce-a10e-e8d50baeb3a2">

Overridden status is now removed from the table

**Comment by deploy-master404** [comment]
Noted, this has been signed off.
