### ISSUE TITLE
[Feature/Enhancement Request]: Secrets/var - Choose Environment has Discard button which is incorrect

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#63]
As a user when I have no changes to save, 'Discard' does not make any logical sense.
<img width="1165" alt="Screenshot 2024-05-09 at 12 18 31 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/0798d1ba-4b84-4c41-b294-3ac0b853db2a">

**Comment by deploy-master404** [comment]
- We need to remove this modal, and on click of secrets & variables - overrides, it would open the side panel with the 1st environment selected by default.

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1556

**Comment by mbhandari31** [comment]
Fixed.
