### ISSUE TITLE
[Bug]: Delete Screen has Delete Variable header even when deleting a secret it has not changed

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#66]
![Uploading Screenshot 2024-05-09 at 12.35.57 PM.png…]()

**Comment by srinikitha6** [comment]
https://github.com/Facets-cloud/facets.cloud/assets/106736846/9a42ce07-dab6-4aa6-b1ac-8219b21f31e7

**Comment by deploy-master404** [comment]
- Header to say 'Delete Secret' when deleting a secret instead of 'Delete Variable'

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1554/files

**Comment by mbhandari31** [comment]
<img width="1432" alt="Screenshot 2024-05-20 at 8 38 01 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/b27a5e1d-4227-4459-a6d4-46c0882ca808">
Fixed.
