### ISSUE TITLE
[Bug]: blueprint text spotted in breadcrumb

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#67]
<img width="448" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/f0d2d703-01cb-40b0-b756-b7fd7eeb5097">

**Comment by 4adway** [comment]
Should be fixed soon. Have added the change.

**Comment by deploy-master404** [comment]
@4adway to merge the changes

**Comment by 4adway** [comment]
PR: https://github.com/Facets-cloud/control-plane-ui/pull/1550

**Comment by deploy-master404** [comment]
@Swathi-P-V please merge this

**Comment by mbhandari31** [comment]
Fixed
