### ISSUE TITLE
Missing Line

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#69]
<img width="524" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/05266d2d-4a2d-4fbd-8e32-ed8755f3bdb1">

**Comment by mbhandari31** [comment]
@Swathi-P-V

**Comment by Swathi-P-V** [comment]
Design of active tab has been changed. This is no more valid issue

**Comment by mbhandari31** [comment]
Fixed.
