### ISSUE TITLE
[Feature/Enhancement Request]:  Git Account facets-substack-github should not be visible/available

### ISSUE THREAD

**Issue by rshreenivas** [Facets-cloud/facets.cloud#7]
Git Account facets-substack-github should not be visible/available, This is internal account only

**Comment by deploy-master404** [comment]
- We currently have it visible/available in the PaaS version as well, would we need to remove from there as well? @bhat-akshay @rshreenivas

**Comment by bhat-akshay** [comment]
New facets bot account added. This should not occur anymore

**Comment by mbhandari31** [comment]
Fixed by @bhat-akshay . Closing it.
<img width="1371" alt="Screenshot 2024-06-27 at 11 28 18 AM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/3dfed3aa-971a-4938-aa2d-61c9585bf9fc">
