### ISSUE TITLE
Wrong Redirection

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#70]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/c9c5743b-7fed-418b-9ac2-50a24565c2c3">

clicking on the environment settings takes me to time sensitive and not to general.

**Comment by deploy-master404** [comment]
@SushmithaFacets 

Could we make the default behaviour as redirecting user to the general tab please?

**Comment by deploy-master404** [comment]
@SushmithaFacets, please drop an update on this once you're back please

**Comment by mbhandari31** [comment]
Fixed by Sushmitha
