### ISSUE TITLE
Misalignment

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#71]
<img width="1234" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/162149fc-304a-4067-910e-0f599f293553">

Release Every field is misaligned

**Comment by mbhandari31** [comment]
Sushmitha is fixing this.

**Comment by deploy-master404** [comment]
- ask rohit about where to put iac version

**Comment by mbhandari31** [comment]
Fixed
