### ISSUE TITLE
[Bug]: Readiness/Liveliness port dropdown is not showing options

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#72]
![Uploading Screenshot 2024-05-09 at 3.27.05 PM.png…]()

**Comment by srinikitha6** [comment]
![Uploading Screenshot 2024-05-09 at 3.27.05 PM.png…]()

**Comment by srinikitha6** [comment]
<img width="1228" alt="Screenshot 2024-05-09 at 3 27 05 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/50779102-ede5-4afa-823b-32d170578f01">

**Comment by deploy-master404** [comment]
@nachiket0310 could you fix this please?

**Comment by mbhandari31** [comment]
<img width="1362" alt="Screenshot 2024-05-20 at 2 17 52 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/c1c4b28d-fccc-42dc-986f-c42a58dff33b">
Fixed
