### ISSUE TITLE
[Bug]: Consistency issue: Artifactory or Container Registry?

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#73]
In the service settings, we are using artifactory but else where we are using container registry. Please make it consistent across.
<img width="1242" alt="Screenshot 2024-05-09 at 3 29 03 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/1fefd4d9-9cb9-4136-a257-15d1b2d9146a">

**Comment by srinikitha6** [comment]
And, can these not be dropdowns?

**Comment by mbhandari31** [comment]
Nachiket is fixing this. And the nomenclature will be same for this now.

**Comment by nachiket0310** [comment]
This section will be removed from Form and configuration altogether as we are following different nomenclature. So, this bug won't be valid in the future
