### ISSUE TITLE
[Bug]: Port name dropdown is not working

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#74]
While configuring a service, I'm unable to add Port Name and the dropdown options are not shown, and it's a mandatory field which is not allowing me to save changes to the configuration.
<img width="1223" alt="Screenshot 2024-05-09 at 5 51 48 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/d083dcf4-3367-4345-9319-e3fe7c167ef8">

**Comment by deploy-master404** [comment]
- in metrics, dropdown, the added ports are not visible in the dropdown

**Comment by deploy-master404** [comment]
- @mbhandari31 to confirm with rohit if metrics needs to be skipped in the form.

if yes, the xui skip can be added from the yaml itself

**Comment by mbhandari31** [comment]
Fixed.
