### ISSUE TITLE
[Bug]: There is no way to delete a single entry when added in the Service Settings

### ISSUE THREAD

**Issue by srinikitha6** [Facets-cloud/facets.cloud#75]
<img width="1232" alt="Screenshot 2024-05-09 at 6 01 27 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/106736846/6135470d-cdd6-4333-a195-f9bc67a5f681">

**Comment by deploy-master404** [comment]
- provide delete option for single entries as well for all(ports, metrics etc)

**Comment by mbhandari31** [comment]
<img width="1102" alt="Screenshot 2024-05-20 at 2 19 39 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/0e3548d9-b0c4-4393-b5e8-f6b81dbce2ab">
Fixed
