### ISSUE TITLE
Side Panel behaviour

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#79]
Side panel should open and close in a similar way. If you're making it "slide in from right" then make the exit same. Don't give it modal's behaviour of closing.

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/cd8e84ca-a417-44d4-adfa-ccf7d6c331f7">

**Comment by mbhandari31** [comment]
Put the same transition while closing the panel as it is when it slides in while opening.

**Comment by mbhandari31** [comment]
Fixed
