### ISSUE TITLE
This is just weird - Overrides environment selection modal

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#82]
We need to rethink this @mbhandari31 . This is a one-off screen. Nowhere in the product have we used such a modal.

<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/a8e6ed03-3e01-4c85-a5f3-8baad89c280b">

**Comment by mbhandari31** [comment]
@dsaini63 Can we come up with a better design for this?

**Comment by mbhandari31** [comment]
Resolved by @4adway
