### ISSUE TITLE
[Bug]: "Add New Service Instance" dialog lacks tooltips

### ISSUE THREAD

**Issue by rr0hit** [Facets-cloud/facets.cloud#9]
The "Add New Service Instance" dialog lacks tooltips. It is not clear what "Repository URL" and "Relative Path" fields are for.

<img width="476" alt="Screenshot 2024-05-02 at 3 12 19 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/594121/ee95785d-c6f8-4c04-a530-af2f62b33c57">

**Comment by mbhandari31** [comment]
> The "Add New Service Instance" dialog lacks tooltips. It is not clear what "Repository URL" and "Relative Path" fields are for.
> 
> <img alt="Screenshot 2024-05-02 at 3 12 19 PM" width="476" src="https://private-user-images.githubusercontent.com/594121/327384710-ee95785d-c6f8-4c04-a530-af2f62b33c57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjYxODUsIm5iZiI6MTcxNDcyNTg4NSwicGF0aCI6Ii81OTQxMjEvMzI3Mzg0NzEwLWVlOTU3ODVkLWM2ZjgtNGMwNC1hNTMwLWFmMmY2MmIzM2M1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODQ0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTE1ZjU1NTBmODhhODAwMGQxYzZiNjA1MDE2OTliZmY1ZTA1ZDE2ZjI4NmNjYWRjNjYwY2RmMzRmZjJiZDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ajR0irlzyXiEOzpA19iSok017iSREu2HQht6o87og3A">
<img width="702" alt="Screenshot 2024-05-03 at 2 41 33 PM" src="https://github.com/Facets-cloud/facets.cloud/assets/162995672/597b8ba9-bb8a-4d4f-af71-c5ece1185df0">

We don't need those 2 fields now. They have been removed and changes are merged

**Comment by mbhandari31** [comment]
Done
