### ISSUE TITLE
Environment Launch Wizard - Secrets and Variables

### ISSUE THREAD

**Issue by dsaini63** [Facets-cloud/facets.cloud#90]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/c5bc9724-b70d-44ac-a9a4-249f1422c7bc">

1. Why is there an environment dropdown above?  @mbhandari31 @deploy-master404 
2. Why is the side panel opening? If it is to add secrets and variables, then the actions are missing.
3. On changing the environment from the dropdown above the table, the page changes in the background and goes to the project level secret and variables.

**Comment by dsaini63** [comment]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/d709df68-da0f-4bee-a0c1-dce87a34a812">


this is where I am once I click on launch.

From here I tried redirecting to the releases page but the launch wizard was opening on its own multiple times even after closing it.

**Comment by dsaini63** [comment]
<img width="1440" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/114902125/0e9759e2-d238-4da9-8f59-6c5dbce31c4e">

!!!!!!!!!!!!!!!!!

**Comment by mbhandari31** [comment]
Fixed.
