### ISSUE TITLE
[Bug]: shows tick in green when the environment is still launching

### ISSUE THREAD

**Issue by krishankirtifacets** [Facets-cloud/facets.cloud#96]
![image](https://github.com/Facets-cloud/facets.cloud/assets/131137614/e2dee0c6-60c5-48ee-8241-f7a559f6ebc1)

**Comment by deploy-master404** [comment]
- Deepak to give the icons for the status and then FE to pick it up.

**Comment by mbhandari31** [comment]
Fixed.
